name: 🐞 Issue report
description: Report an issue in Komikku 2026
labels: [bug]
body:
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you should expect to happen.
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Explain what actually happens.
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: textarea
    id: crash-logs
    attributes:
      label: Crash logs
      description: |
        If you're experiencing crashes, go to the app's **More → Settings → Advanced** page, press **Dump crash logs** and share the crash logs here.
      placeholder: |
        You can upload the crash log file as an attachment, or paste the crash logs in plain text if needed.

  - type: input
    id: app-version
    attributes:
      label: Komikku 2026 version
      description: You can find your app version in **More → About**.
      placeholder: |
        Example: "0.1.0-alpha"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android version
      description: You can find this in your Android settings.
      placeholder: |
        Example: "Android 14"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      description: List your device and model.
      placeholder: |
        Example: "Google Pixel 8"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Read this carefully, we will close and ignore your issue if you skimmed through this.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I have updated the app to the **[latest version](https://github.com/Heartless-Veteran/komikku-2026/releases/latest)**.
          required: true
        - label: I have filled out all of the requested information in this form, including specific version numbers.
          required: true
        - label: I understand that **Komikku 2026 does not maintain or fix extensions**, and I **will not receive help** for issues related to sources or extensions.
          required: true

  - type: "textarea"
    id: "prioritisation"
    attributes:
      label: "Is this issue important to you?"
      description: |
        **Please do not modify this text area!**

        This template lets users vote with a 👍 reaction if they find it important.
        This is not a guarantee that highly-requested issues will be fixed first, but it helps prioritisation.
      value: |
        Add a 👍 [reaction] to [issues you find important].

        [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [issues you find important]: https://github.com/Heartless-Veteran/komikku-2026/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
